# Generated by Django 6.0 on 2025-12-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_profile_workingdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='service',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
