# Generated by Django 6.0 on 2025-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_workingdays_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingdays',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workingdays',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
